apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://*:6001
  DatabaseConnection__Host: db-service
  DatabaseConnection__Username: root
  DatabaseConnection__Password: MySql2022
  DatabaseConnection__Database: "todoapidb"
  RabbitMQ__Host: rabbitmq-service
  RabbitMQ__Queue: TodoQueue
  Elasticsearch__Uri: "http://elasticsearch-service:9200"
