filebeat.inputs:
  - type: container
    paths: 
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_host_metadata:
      host: '{{ hostv4 }}'
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["localhost:5044"]
  indices:
    - index: "todo-api-%{[agent.version]}"

logging.json: true
logging.metrics.enabled: false