apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-rabbitmq
  template:
    metadata:
      labels:
        app: todo-rabbitmq
    spec:
      containers:
      - name: todo-rabbitmq
        image: rabbitmq:3
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5672
        envFrom:
        - configMapRef:
            name: rabbitmq-configmap
        
