apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  type: NodePort
  selector: 
    app: todo-kibana
  ports: 
    - port: 5601          # ouve na porta 5601
      targetPort: 5601    # redireciona para o POD que ouve na porta 6002
      nodePort: 30001     # porta para acesso externo - de 30000 a 32767