apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-kibana
  template:
    metadata:
      labels:
        app: todo-kibana
    spec:
      containers:
      - name: todo-kibana
        image: docker.elastic.co/kibana/kibana:7.11.1
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 5601
        envFrom:
        - configMapRef:
            name: kibana-configmap
        
