apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-static
  template:
    metadata:
      labels:
        app: todo-app-static
    spec:
      containers:
      - name: todo-app-static
        image: vitormoschetta/todoapp.static:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6003        
        
