apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector: 
    app: todo-app    
  ports: 
    - port: 6003          # ouve na porta 6002
      targetPort: 6003    # redireciona para o POD que ouve na porta 6002
      nodePort: 30001     # porta para acesso externo - de 30000 a 32767